name: Scrape Data Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t scraper_image .

    # Step 4: Create a folder for output and run the container
    - name: Run Docker container and save data
      run: |
        mkdir -p output_data
        docker run -v $(pwd)/output_data:/data scraper_image

    # Step 5: Upload the output file as an artifact
    - name: Upload scraped data
      uses: actions/upload-artifact@v3
      with:
        name: scraped-data
        path: output_data/scraped_data.csv
